# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f $HOME/.profile ]; then
	. $HOME/.profile
fi

# User specific aliases and functions
export HISTSIZE=1000000

if [ -d $HOME/.rvm ]; then
	PATH=$PATH:$HOME/.local/bin:$HOME/bin
	export PATH
	[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
fi
